require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "config/**/*"
    - "spec/**/*"

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25
