version: "3"
services:
  web:
    build: .
    command: >
      bash -c "rm -f /movie_bbs/tmp/pids/server.pid
      && dockerize -wait tcp://db:3306 -timeout 20s
      && bundle exec unicorn -p 3000 -c /movie_bbs/config/unicorn.conf.rb"
    stdin_open: true
    tty: true
    volumes:
      - .:/movie_bbs
      - node_modules:/movie_bbs/node_modules
      - tmp-data:/movie_bbs/tmp/sockets
      - public-data:/movie_bbs/public
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - tmp-data:/movie_bbs/tmp/sockets
      - public-data:/movie_bbs/public
    depends_on:
      - web

volumes:
  mysql-data:
    driver: local
  node_modules:
    driver: local
  tmp-data:
    driver: local
  public-data:
    driver: local
